AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  de.probstl.aws.MoneyHandlerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java8
      Handler: de.probstl.aws.de.probstl.aws.MoneyHandler::handleRequest
      Timeout: 60
      CodeUri: ./target/lambda.jar
